logging:
  level:
    io.github.artemptushkin.ai.assistants: debug
    org.springframework.http.client: DEBUG
http-clients:
  clients:
    gitlab:
      host: gitlab.com
    alpha-vantage:
      host: www.alphavantage.co
    coinmarketcap:
      host: pro-api.coinmarketcap.com
server:
  shutdown: graceful
spring:
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
  cloud:
    gcp:
      logging:
        enabled: false
      trace:
        enabled: true
