spring:
  profiles:
    include: secret
logging:
  level:
    io.github.artemptushkin.ai.assistants: debug
    org.springframework.http.client: DEBUG
http-clients:
  clients:
    gitlab:
      host: gitlab.com
    alpha-vantage:
      host: www.alphavantage.co
    coinmarketcap:
      host: pro-api.coinmarketcap.com
