spring:
  profiles:
    include: secret
logging:
  level:
    io.github.artemptushkin.ai.assistants: debug
    org.springframework.http.client: DEBUG
gitlab:
  host: "https://gitlab.com"
alpha-vantage:
  host: www.alphavantage.co
