telegram:
  bot:
    isOnboardingEnabled: true
    startMessage: "Hi! I will help you learn Dutch! Let’s choose your training level."
    metadata:
      language: Dutch
    buttons:
      - id: add-words
        text: "Add words"
        isBlocking: true
      - id: delete-workds
        text: "Delete words"
        isBlocking: true
      - id: create-story
        text: "Create story"
        isBlocking: false